// Modal
export const GATH_CREATE_MODAL_ON = "GATH_CREATE_MODAL_ON";
export const GATH_DETAIL_MODAL_ON = "GATH_DETAIL_MODAL_ON";
export const CONFIRM_MODAL_ON = "CONFIRM_MODAL_ON";
export const MODAL_OFF = "MODAL_OFF";
